# Generated by Django 5.2.15 on 2026-06-09 18:11

import django.db.models.deletion
import store.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome do pacote')),
                ('quantity', models.PositiveIntegerField(help_text='Quantidade enviada para a integração externa.', verbose_name='quantidade')),
                ('price_brl', models.DecimalField(decimal_places=2, help_text='Preço final manual cobrado do cliente.', max_digits=12, verbose_name='preço em reais')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('featured', models.BooleanField(default=False, verbose_name='destaque')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
            ],
            options={
                'verbose_name': 'pacote',
                'verbose_name_plural': 'pacotes',
                'ordering': ('position', 'quantity'),
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
            ],
            options={
                'verbose_name': 'plataforma',
                'verbose_name_plural': 'plataformas',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=store.models.generate_order_code, editable=False, max_length=20, unique=True, verbose_name='código')),
                ('platform_name', models.CharField(max_length=80, verbose_name='plataforma')),
                ('service_name', models.CharField(max_length=120, verbose_name='serviço')),
                ('package_name', models.CharField(max_length=120, verbose_name='pacote')),
                ('provider_service_id', models.CharField(editable=False, max_length=100, verbose_name='provider_service_id')),
                ('target', models.CharField(max_length=500, verbose_name='link ou @perfil')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='total')),
                ('whatsapp', models.CharField(max_length=30, verbose_name='WhatsApp')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('accepted_terms', models.BooleanField(default=False, verbose_name='aceitou os termos')),
                ('accepted_terms_at', models.DateTimeField(blank=True, null=True, verbose_name='aceite registrado em')),
                ('terms_version', models.CharField(blank=True, max_length=30, verbose_name='versão dos termos')),
                ('confirmed_public_profile', models.BooleanField(default=False, verbose_name='confirmou perfil público')),
                ('profile_username', models.CharField(blank=True, max_length=160, verbose_name='usuário do perfil')),
                ('profile_picture_url', models.URLField(blank=True, max_length=1000, verbose_name='foto do perfil')),
                ('profile_is_public', models.BooleanField(blank=True, null=True, verbose_name='perfil público')),
                ('profile_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='perfil verificado em')),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do cliente')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='user agent')),
                ('payment_status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('paid', 'Pago'), ('rejected', 'Rejeitado'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('error', 'Erro')], default='pending', max_length=20, verbose_name='status do pagamento')),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('submitting', 'Processando'), ('submitted', 'Pedido enviado'), ('error', 'Erro no processamento')], default='pending', max_length=20, verbose_name='status do pedido')),
                ('external_order_id', models.CharField(blank=True, max_length=100, verbose_name='ID externo do pedido')),
                ('external_status', models.CharField(blank=True, max_length=100, verbose_name='status externo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='store.package', verbose_name='pacote')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('charge', 'Cobrança criada'), ('webhook', 'Webhook recebido'), ('status', 'Status consultado'), ('error', 'Erro')], max_length=20, verbose_name='evento')),
                ('external_payment_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='ID externo do pagamento')),
                ('status', models.CharField(blank=True, max_length=50, verbose_name='status')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor')),
                ('pix_code', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('qr_code_base64', models.TextField(blank=True, verbose_name='QR Code em base64')),
                ('payment_url', models.URLField(blank=True, max_length=1000, verbose_name='link do pagamento')),
                ('signature_valid', models.BooleanField(default=False, verbose_name='assinatura válida')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='resposta sanitizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_logs', to='store.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'log de pagamento',
                'verbose_name_plural': 'logs de pagamento',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProviderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Informação'), ('error', 'Erro')], default='info', max_length=10, verbose_name='nível')),
                ('action', models.CharField(max_length=100, verbose_name='ação')),
                ('message', models.TextField(verbose_name='mensagem')),
                ('response_data', models.JSONField(blank=True, default=dict, verbose_name='resposta sanitizada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_logs', to='store.order', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'log de integração',
                'verbose_name_plural': 'logs de integração',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(blank=True)),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('provider_service_id', models.CharField(help_text='ID técnico do serviço configurado na integração externa.', max_length=100, verbose_name='provider_service_id')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='store.platform', verbose_name='plataforma')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
                'ordering': ('position', 'name'),
            },
        ),
        migrations.AddField(
            model_name='package',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='packages', to='store.service', verbose_name='serviço'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['code'], name='store_order_code_5466bc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_status', 'fulfillment_status'], name='store_order_payment_e63d1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.UniqueConstraint(fields=('platform', 'slug'), name='unique_service_slug_per_platform'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.UniqueConstraint(fields=('service', 'quantity'), name='unique_package_quantity_per_service'),
        ),
    ]
