# Generated by Django 5.2.15 on 2026-06-09 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='provider_service_id',
            field=models.CharField(blank=True, help_text='ID técnico do serviço configurado na integração externa.', max_length=100, verbose_name='provider_service_id'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=120, verbose_name='serviço')),
                ('package_name', models.CharField(max_length=120, verbose_name='pacote')),
                ('provider_service_id', models.CharField(editable=False, max_length=100, verbose_name='provider_service_id')),
                ('target', models.CharField(max_length=500, verbose_name='link ou @perfil')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantidade')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('fulfillment_status', models.CharField(choices=[('pending', 'Aguardando pagamento'), ('submitting', 'Processando'), ('submitted', 'Pedido enviado'), ('error', 'Erro no processamento')], default='pending', max_length=20, verbose_name='status')),
                ('external_order_id', models.CharField(blank=True, max_length=100, verbose_name='ID externo')),
                ('external_status', models.CharField(blank=True, max_length=100, verbose_name='status externo')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='pedido')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.package', verbose_name='pacote')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'ordering': ('id',),
                'constraints': [models.UniqueConstraint(fields=('order', 'package'), name='unique_package_per_order')],
            },
        ),
    ]
