# Generated by Django 5.2.15 on 2026-06-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_payment_provider_fields_and_service_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments_text',
            field=models.TextField(blank=True, max_length=20000, verbose_name='comentários personalizados'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='comments_text',
            field=models.TextField(blank=True, max_length=20000, verbose_name='comentários personalizados'),
        ),
        migrations.AddField(
            model_name='service',
            name='requires_comments',
            field=models.BooleanField(default=False, help_text='Solicita um comentário por linha no checkout.', verbose_name='exige comentários personalizados'),
        ),
    ]
