# Generated by Django 5.2.15 on 2026-06-19 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_comments_text_orderitem_comments_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fb_fbc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta _fbc'),
        ),
        migrations.AddField(
            model_name='order',
            name='fb_fbp',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta _fbp'),
        ),
    ]
