# Generated by Django 5.2.15 on 2026-06-29 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_fb_fbc_order_fb_fbp'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='pergunta')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'pergunta do quiz',
                'verbose_name_plural': 'perguntas do quiz',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título interno')),
                ('layout', models.CharField(choices=[('3x2', '3×2 (6 pacotes)'), ('3x3', '3×3 (9 pacotes)')], default='3x2', max_length=3, verbose_name='layout da grade')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'resultado do quiz',
                'verbose_name_plural': 'resultados do quiz',
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, verbose_name='opção')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='posição')),
                ('next_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_options', to='store.quizquestion', verbose_name='próxima pergunta')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='store.quizquestion', verbose_name='pergunta')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggering_options', to='store.quizresult', verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'opção do quiz',
                'verbose_name_plural': 'opções do quiz',
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='QuizResultPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='1 a 6 para grade 3×2; 1 a 9 para grade 3×3.', verbose_name='posição na grade')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_result_packages', to='store.package', verbose_name='pacote')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_packages', to='store.quizresult', verbose_name='resultado')),
            ],
            options={
                'verbose_name': 'pacote do resultado',
                'verbose_name_plural': 'pacotes do resultado',
                'ordering': ('position',),
                'constraints': [models.UniqueConstraint(fields=('result', 'position'), name='unique_position_per_result')],
            },
        ),
    ]
